version: '3'

services:
  php:
    container_name: "php-fpm"
    build:
      context: ./docker/php
    environment:
      - APP_ENV=dev
      - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
    volumes:
      - ./:/var/www

  nginx:
      container_name: "nginx"
      build:
        context: ./docker/nginx
      volumes:
        - ./:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/logs:/var/log
      depends_on:
        - php
      ports:
        - "80:80"

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./dump:/dump
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ultima
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 33060:3306
    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
